name: nextcloud_sync
description: A nextcloud sync programm for the Viktoriaschule Aachen
version: 1.0.2+3

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  nextcloud:
  dio:
  shared_preferences:
  after_layout:
  archive:
  crypto:
  flutter_event_bus:
  package_info:

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: Roboto
      fonts:
        - asset: fonts/Roboto-Regular.ttf